import Head from "next/head"
import Header from "../components/Header"
import SpellCard from "../components/SpellCard"

export default function Home({ spells }) {
  return (
    <div className="container mx-auto">
      <Head>
        <title>D&D Spellbook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <section className="pt-2 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 list-none">
          {spells.map((spell) => (
            <SpellCard spell={spell} key={spell.id} />
          ))}
        </section>
      </main>
      <footer>Copyright stuff...</footer>
    </div>
  )
}
